export const About = () => {
    return (
        <>
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi, rem mollitia hic corrupti quas dolorem labore. Aliquid sint magnam ad rem accusantium ipsam aperiam minima? Totam, quis molestias illo harum, praesentium ipsum, est nihil fuga iusto recusandae doloribus delectus quidem voluptates dolorum necessitatibus? Fuga, ullam? Rem quisquam obcaecati, voluptate quo nisi doloribus, commodi adipisci mollitia a facere velit. Eligendi incidunt, sit suscipit quaerat eaque quas laboriosam veritatis et maiores ea a impedit dolor vero corrupti similique! Quos earum pariatur cum minima expedita dolore qui accusamus voluptatibus, autem quaerat animi laborum, labore nam dolor fugit suscipit optio culpa eaque architecto laboriosam reprehenderit non tempore harum. Voluptates suscipit dolor esse porro laudantium architecto eos commodi in adipisci dicta voluptas non sint qui voluptatum et eius sed aperiam temporibus doloremque cum, ipsam dolores? Mollitia est officia sapiente veniam, dicta hic voluptate. Ad id placeat eaque earum ullam, deleniti quasi! In quasi culpa alias delectus ipsam quidem commodi velit deleniti molestias aut. Nam voluptatem soluta aliquid reiciendis. Nisi maxime rem deserunt veritatis optio sequi iure rerum, explicabo expedita quaerat nulla atque, suscipit magnam reprehenderit aliquam iusto cumque vitae esse? Nemo architecto quos officiis sed nam assumenda voluptates temporibus cum quibusdam, obcaecati illum distinctio earum, velit, totam deleniti quaerat quis molestiae modi? Quo repellendus molestias ipsam architecto aliquam accusantium odio iusto nisi, veniam et tempora ratione voluptates, repudiandae totam quibusdam quos quod doloremque consequatur voluptatem rem vitae magni libero perferendis! Aut aliquam in, officiis molestiae repudiandae a et est tempora vel quae voluptates, optio sed placeat ad! Minima et sed tempora ullam reprehenderit eveniet magnam odio tenetur ducimus sint repellendus sunt consequuntur velit maxime quod odit, voluptate voluptates libero rem fugit laborum error quasi enim nesciunt. Ipsa ab ut soluta officia nam! Quisquam eaque quasi, numquam deserunt consequatur quaerat, quae atque suscipit eligendi culpa esse.</p>
            
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor autem nihil repudiandae sunt quidem porro, quaerat, repellat molestiae odio eligendi, minus possimus. Expedita sapiente eius deleniti alias eveniet esse corporis accusantium iure amet aut optio, quo, quia nemo! Corporis est, doloremque quibusdam totam vel ipsam blanditiis harum placeat quasi non debitis voluptatem quia natus dolorum libero doloribus! Adipisci nemo facilis ut quas optio praesentium, officia temporibus esse tempore voluptate nulla quisquam sequi vitae molestiae natus dolores. Tenetur reprehenderit natus modi inventore ratione sit vero molestiae, deleniti placeat tempora deserunt facilis nam? Commodi nobis voluptates quis illum atque quam, corrupti minus!</p>
        </>
    )
}
